services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./graphs:/app/graphs
  
volumes:
  logs:
    external: true
  graphs:
    external: true