apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server-run
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server-run
  template:
    metadata:
      labels:
        app: go-server-run
    spec:
      containers:
      - name: go-container-run
        image: feribarra27/go-server-run:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: "50m"
            memory: "32Mi"
          limits:
            cpu: "100m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: go-service-run
spec:
  selector:
    app: go-server-run
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
