apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
    resources:
      requests:
        memory: "256Mi"
        cpu: "150m"
      limits:
        memory: "1Gi"
        cpu: "200m"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 5Gi
          deleteClaim: false
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: "128Mi"    # Reduce los recursos solicitados para Zookeeper
        cpu: "100m"
      limits:
        memory: "256Mi"    # Limita los recursos máximos para Zookeeper
        cpu: "200m"
    storage:
      type: persistent-claim
      size: 3Gi
      deleteClaim: false
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: "96Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
    userOperator:
      resources:
        requests:
          memory: "96Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"