datasources:
  - name: Redis
    type: redis-datasource
    access: proxy
    isDefault: true
    orgId: 1
    url: redis://redis-service:6379
    uid: M1R3D1SP4SSW0RD
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true
    secureJsonData:
      password: M1R3D1SP4SSW0RD
    version: 1
  - name: Prometheus
    type: prometheus
    access: proxy
    isDefault: false
    orgId: 1
    url: http://prometheus-service:9090
    uid: M1PR0M3TH3USP4SSW0RD
    editable: true
    version: 1