apiVersion: 1

datasources:
  - name: Redis
    type: redis-datasource
    access: proxy
    isDefault: true
    orgId: 1
    url: redis://redis-service:6379
    uid: M1R3D1SP4SSW0RD
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true
    secureJsonData:
      password: M1R3D1SP4SSW0RD

    apiVersion: 1