{
 "title": "Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pods running by nodes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_running_pods{job=\"kubernetes-nodes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk by Pods",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_disk_filesystem_info{namespace=\"default\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory By Namespace",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"default\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"kafka\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"ingress-nginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU System Namespace default",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_system_seconds_total{namespace=\"default\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_cpu_system_seconds_total{namespace=\"kafka\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_cpu_system_seconds_total{namespace=\"ingress-nginx\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}